username = "your username or email"
password = "your password"
branch = "default"
# optional:
# ptr = false
# hostname = "screeps.com"
# ssl = true
# port = 443
# # use absolute file path to get out of "target/"
# ouptut_js_file = "main.js"
# output_wasm_file = "compiled.wasm"
